/**
 * Generate docs/benchmarks.md (and the Chinese mirror) from archived
 * bench-results/browser-*.json reports, so the browser benchmark trend is a
 * reviewed artifact instead of tribal knowledge.
 *
 * For each metric the doc shows the most recent value, the previous archived
 * value, the delta, and a running all-time best. Machine-generated content
 * (the tables) is delimited so regeneration overwrites only that section.
 *
 * Usage: node scripts/bench-trend.mjs
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const resultsDir = resolve('bench-results');
const METRICS = {
  publish: [
    { path: 'perMessageMs', label: 'publish per-message (ms, lower is better)', note: 'measured per worker mode (dedicated / shared)' }
  ],
  databus: [
    { path: 'wildcardDispatch1000Ms', label: 'wildcard dispatch ×1000 (ms, lower is better)' },
    { path: 'publishBatch1000Ms', label: 'publishBatch ×1000 (ms, lower is better)' },
    { path: 'dedup1000Ms', label: 'dedup ×1000 (ms, lower is better)' },
    { path: 'traceAndPublish1000Ms', label: 'trace + publish ×1000 (ms, lower is better)' },
    { path: 'firstPacketMs', label: 'first-packet cold dispatch (ms, lower is better)' }
  ]
};

const files = readdirSync(resultsDir)
  .filter(name => name.startsWith('browser-') && name.endsWith('.json'))
  .sort();

if (files.length < 2) {
  console.error('Need at least two archived reports in bench-results/ (run pnpm bench:browser twice).');
  process.exit(1);
}

const reports = files.map(name => {
  const report = JSON.parse(readFileSync(join(resultsDir, name), 'utf8'));
  return { name, report };
});

/** Flatten one report into `metricKey → value` entries (mode-suffixed for publish). */
function collect(report) {
  const entries = {};
  for (const result of report.results ?? []) {
    entries[`publish/${result.mode}`] = result.perMessageMs;
  }
  for (const [key, value] of Object.entries(report.databus?.timings ?? {})) {
    entries[`databus/${key}`] = value;
  }
  return entries;
}

const current = reports.at(-1);
const previous = reports.at(-2);

// All-time best per metric across the archive (min, since every metric is a
// latency where lower is better).
const best = {};
for (const { report } of reports) {
  for (const [key, value] of Object.entries(collect(report))) {
    if (typeof value === 'number' && (best[key] === undefined || value < best[key])) best[key] = value;
  }
}

const now = new Date().toISOString().slice(0, 10);
const cur = collect(current.report);
const prev = collect(previous.report);

function table(locale) {
  const th = locale === 'zh' ? ['指标', '上次 (ms)', '本次 (ms)', 'Δ', '历史最优 (ms)'] : ['Metric', 'Previous (ms)', 'Latest (ms)', 'Δ', 'All-time best (ms)'];
  const lines = [
    `| ${th[0]} | ${th[1]} | ${th[2]} | ${th[3]} | ${th[4]} |`,
    `|---|---|---|---|---|`
  ];
  for (const [group, metrics] of Object.entries(METRICS)) {
    for (const metric of metrics) {
      if (group === 'publish') {
        for (const mode of ['dedicated', 'shared']) {
          const key = `${group}/${mode}`;
          if (cur[key] === undefined) continue;
          const delta = prev[key] === undefined ? 'n/a' : `${cur[key] - prev[key] >= 0 ? '+' : ''}${(cur[key] - prev[key]).toFixed(2)}`;
          const name = `${metric.label} — ${mode}`;
          lines.push(`| ${name} | ${prev[key] ?? 'n/a'} | ${cur[key]} | ${delta} | ${best[key]} |`);
        }
        continue;
      }
      const key = `${group}/${metric.path}`;
      if (cur[key] === undefined) continue;
      const delta = prev[key] === undefined ? 'n/a' : `${cur[key] - prev[key] >= 0 ? '+' : ''}${(cur[key] - prev[key]).toFixed(2)}`;
      lines.push(`| ${metric.label} | ${prev[key] ?? 'n/a'} | ${cur[key]} | ${delta} | ${best[key]} |`);
    }
  }
  return lines.join('\n');
}

const en = [
  '<!-- Generated by scripts/bench-trend.mjs — tables between the BEGIN/END markers are regenerated; prose is maintained by hand. -->',
  '',
  '# Browser Benchmark Trend',
  '',
  `> Auto-generated ${now} from ${files.length} archived \`bench-results/browser-*.json\` reports (run \`pnpm bench:browser\` to add one; regenerate this doc with \`node scripts/bench-trend.mjs\`).`,
  '',
  'The comparison baseline for release gating is `pnpm bench:compare --fail-above-pct 50` between the two most recent reports (50% ceiling absorbs shared-runner noise). This doc records the long-run picture: values are per-metric latencies where lower is better, and the all-time best marks the healthiest observed run on this machine.',
  '',
  '<!-- BENCH-TREND:BEGIN (machine-generated) -->',
  table('en'),
  '<!-- BENCH-TREND:END -->',
  '',
  'Notes:',
  '',
  '- publish rows measure the full demo round-trip (publish click → transport → demo server → EVENT fan-out → receiver metric), so they include real browser and server latency; the databus rows are in-page hot-path microbenchmarks.',
  '- A sustained upward drift across several runs — not a single outlier — is the regression signal. Investigate the hot-path changes in that window before tagging a release.'
].join('\n');

const zh = [
  '<!-- 由 scripts/bench-trend.mjs 生成 —— BEGIN/END 标记之间的表格为机器再生成，文字部分人工维护。 -->',
  '',
  '# 浏览器基准趋势',
  '',
  `> ${now} 自动生成，基于 ${files.length} 份归档的 \`bench-results/browser-*.json\` 报告（运行 \`pnpm bench:browser\` 追加一份；用 \`node scripts/bench-trend.mjs\` 重新生成本文档）。`,
  '',
  '发布门禁的对比基线是最近两份报告之间的 `pnpm bench:compare --fail-above-pct 50`（50% 上限用于吸收共享 runner 的噪声）。本文记录长期趋势：数值为逐指标延迟，越低越好；历史最优为本机观察到的最健康一次运行。',
  '',
  '<!-- BENCH-TREND:BEGIN (machine-generated) -->',
  table('zh'),
  '<!-- BENCH-TREND:END -->',
  '',
  '说明：',
  '',
  '- publish 行测量完整演示链路（发布点击 → transport → 演示服务器 → EVENT 扇出 → 接收方指标），包含真实浏览器与服务器延迟；databus 行是页内热路径微基准。',
  '- 回归信号是多轮持续上移，而不是单次离群值。打 tag 发布前，应排查对应窗口内的热路径改动。'
].join('\n');

writeFileSync(resolve('docs/benchmarks.md'), `${en}\n`);
writeFileSync(resolve('docs/zh/benchmarks.md'), `${zh}\n`);
console.log(`docs/benchmarks.md + docs/zh/benchmarks.md generated from ${files.length} reports (latest: ${current.name}).`);
